
package CAMPUSonline::ThesisElements::getAllThesesMetadataResponse;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.campusonline.at/thesisservice/basetypes' }

__PACKAGE__->__set_name('getAllThesesMetadataResponse');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %thesis_of :ATTR(:get<thesis>);
my %errorCode_of :ATTR(:get<errorCode>);
my %errorMessage_of :ATTR(:get<errorMessage>);

__PACKAGE__->_factory(
    [ qw(        thesis
        errorCode
        errorMessage

    ) ],
    {
        'thesis' => \%thesis_of,
        'errorCode' => \%errorCode_of,
        'errorMessage' => \%errorMessage_of,
    },
    {
        'thesis' => 'CAMPUSonline::ThesisTypes::Thesis',
        'errorCode' => 'SOAP::WSDL::XSD::Typelib::Builtin::int',
        'errorMessage' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
    },
    {

        'thesis' => 'thesis',
        'errorCode' => 'errorCode',
        'errorMessage' => 'errorMessage',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CAMPUSonline::ThesisElements::getAllThesesMetadataResponse

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
getAllThesesMetadataResponse from the namespace http://www.campusonline.at/thesisservice/basetypes.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * thesis

 $element->set_thesis($data);
 $element->get_thesis();




=item * errorCode

 $element->set_errorCode($data);
 $element->get_errorCode();




=item * errorMessage

 $element->set_errorMessage($data);
 $element->get_errorMessage();





=back


=head1 METHODS

=head2 new

 my $element = CAMPUSonline::ThesisElements::getAllThesesMetadataResponse->new($data);

Constructor. The following data structure may be passed to new():

 {
   thesis =>  { # CAMPUSonline::ThesisTypes::Thesis
     ID =>  $some_value, # long
     attr =>  { value => $some_value },
     metaclass =>  { # CAMPUSonline::ThesisTypes::Metaclass
       name => $some_value, # SimpleNameType
       metaobj =>  { # CAMPUSonline::ThesisTypes::Metaobj
         type => $some_value, # SimpleTypeType
         attr =>  { value => $some_value },
       },
     },
   },
   errorCode =>  $some_value, # int
   errorMessage =>  $some_value, # string
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

