
package CAMPUSonline::ThesisElements::getDocumentByThesisIDRequest;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.campusonline.at/thesisservice/basetypes' }

__PACKAGE__->__set_name('getDocumentByThesisIDRequest');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %token_of :ATTR(:get<token>);
my %ID_of :ATTR(:get<ID>);
my %docType_of :ATTR(:get<docType>);

__PACKAGE__->_factory(
    [ qw(        token
        ID
        docType

    ) ],
    {
        'token' => \%token_of,
        'ID' => \%ID_of,
        'docType' => \%docType_of,
    },
    {
        'token' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ID' => 'SOAP::WSDL::XSD::Typelib::Builtin::long',
        'docType' => 'CAMPUSonline::ThesisTypes::SimpleDocType',
    },
    {

        'token' => 'token',
        'ID' => 'ID',
        'docType' => 'docType',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CAMPUSonline::ThesisElements::getDocumentByThesisIDRequest

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
getDocumentByThesisIDRequest from the namespace http://www.campusonline.at/thesisservice/basetypes.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * token

 $element->set_token($data);
 $element->get_token();




=item * ID

 $element->set_ID($data);
 $element->get_ID();




=item * docType

 $element->set_docType($data);
 $element->get_docType();





=back


=head1 METHODS

=head2 new

 my $element = CAMPUSonline::ThesisElements::getDocumentByThesisIDRequest->new($data);

Constructor. The following data structure may be passed to new():

 {
   token =>  $some_value, # string
   ID =>  $some_value, # long
   docType => $some_value, # SimpleDocType
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

