
package CAMPUSonline::ThesisElements::getMetadataByThesisIDRequest;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.campusonline.at/thesisservice/basetypes' }

__PACKAGE__->__set_name('getMetadataByThesisIDRequest');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %token_of :ATTR(:get<token>);
my %ID_of :ATTR(:get<ID>);
my %attr_of :ATTR(:get<attr>);
my %classAttrKeySet_of :ATTR(:get<classAttrKeySet>);

__PACKAGE__->_factory(
    [ qw(        token
        ID
        attr
        classAttrKeySet

    ) ],
    {
        'token' => \%token_of,
        'ID' => \%ID_of,
        'attr' => \%attr_of,
        'classAttrKeySet' => \%classAttrKeySet_of,
    },
    {
        'token' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ID' => 'SOAP::WSDL::XSD::Typelib::Builtin::long',
        'attr' => 'CAMPUSonline::ThesisTypes::AttrKey',
        'classAttrKeySet' => 'CAMPUSonline::ThesisTypes::ClassAttrKeySet',
    },
    {

        'token' => 'token',
        'ID' => 'ID',
        'attr' => 'attr',
        'classAttrKeySet' => 'classAttrKeySet',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CAMPUSonline::ThesisElements::getMetadataByThesisIDRequest

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
getMetadataByThesisIDRequest from the namespace http://www.campusonline.at/thesisservice/basetypes.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * token

 $element->set_token($data);
 $element->get_token();




=item * ID

 $element->set_ID($data);
 $element->get_ID();




=item * attr

 $element->set_attr($data);
 $element->get_attr();




=item * classAttrKeySet

 $element->set_classAttrKeySet($data);
 $element->get_classAttrKeySet();





=back


=head1 METHODS

=head2 new

 my $element = CAMPUSonline::ThesisElements::getMetadataByThesisIDRequest->new($data);

Constructor. The following data structure may be passed to new():

 {
   token =>  $some_value, # string
   ID =>  $some_value, # long
   attr => ,
   classAttrKeySet =>  { # CAMPUSonline::ThesisTypes::ClassAttrKeySet
     name => $some_value, # SimpleNameType
     attr => ,
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

