
package CAMPUSonline::ThesisElements::setPlagResultByThesisIDRequest;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.campusonline.at/thesisservice/basetypes' }

__PACKAGE__->__set_name('setPlagResultByThesisIDRequest');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %token_of :ATTR(:get<token>);
my %ID_of :ATTR(:get<ID>);
my %plagiarismReport_of :ATTR(:get<plagiarismReport>);

__PACKAGE__->_factory(
    [ qw(        token
        ID
        plagiarismReport

    ) ],
    {
        'token' => \%token_of,
        'ID' => \%ID_of,
        'plagiarismReport' => \%plagiarismReport_of,
    },
    {
        'token' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ID' => 'SOAP::WSDL::XSD::Typelib::Builtin::long',
        'plagiarismReport' => 'CAMPUSonline::ThesisTypes::PlagReport',
    },
    {

        'token' => 'token',
        'ID' => 'ID',
        'plagiarismReport' => 'plagiarismReport',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CAMPUSonline::ThesisElements::setPlagResultByThesisIDRequest

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
setPlagResultByThesisIDRequest from the namespace http://www.campusonline.at/thesisservice/basetypes.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * token

 $element->set_token($data);
 $element->get_token();




=item * ID

 $element->set_ID($data);
 $element->get_ID();




=item * plagiarismReport

 $element->set_plagiarismReport($data);
 $element->get_plagiarismReport();





=back


=head1 METHODS

=head2 new

 my $element = CAMPUSonline::ThesisElements::setPlagResultByThesisIDRequest->new($data);

Constructor. The following data structure may be passed to new():

 {
   token =>  $some_value, # string
   ID =>  $some_value, # long
   plagiarismReport =>  { # CAMPUSonline::ThesisTypes::PlagReport
     reportUUID =>  $some_value, # string
     submissionDate =>  $some_value, # dateTime
     reportDate =>  $some_value, # dateTime
     serviceName =>  $some_value, # string
     pop =>  $some_value, # float
     reportDoc =>  { # CAMPUSonline::ThesisTypes::PlagiatsDoc
       fileName =>  $some_value, # string
       mimeType => $some_value, # SimpleMimeType
       fileSize =>  $some_value, # long
       fileCreatedOn =>  $some_value, # dateTime
       fileChangedOn =>  $some_value, # dateTime
       content =>  $some_value, # base64Binary
     },
   },
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

