
package CAMPUSonline::ThesisElements::setThesisStatusByIDRequest;
use strict;
use warnings;

{ # BLOCK to scope variables

sub get_xmlns { 'http://www.campusonline.at/thesisservice/basetypes' }

__PACKAGE__->__set_name('setThesisStatusByIDRequest');
__PACKAGE__->__set_nillable();
__PACKAGE__->__set_minOccurs();
__PACKAGE__->__set_maxOccurs();
__PACKAGE__->__set_ref();

use base qw(
    SOAP::WSDL::XSD::Typelib::Element
    SOAP::WSDL::XSD::Typelib::ComplexType
);

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %token_of :ATTR(:get<token>);
my %ID_of :ATTR(:get<ID>);
my %status_of :ATTR(:get<status>);
my %statusDate_of :ATTR(:get<statusDate>);

__PACKAGE__->_factory(
    [ qw(        token
        ID
        status
        statusDate

    ) ],
    {
        'token' => \%token_of,
        'ID' => \%ID_of,
        'status' => \%status_of,
        'statusDate' => \%statusDate_of,
    },
    {
        'token' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'ID' => 'SOAP::WSDL::XSD::Typelib::Builtin::long',
        'status' => 'CAMPUSonline::ThesisTypes::SimpleStateType',
        'statusDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
    },
    {

        'token' => 'token',
        'ID' => 'ID',
        'status' => 'status',
        'statusDate' => 'statusDate',
    }
);

} # end BLOCK






} # end of BLOCK



1;


=pod

=head1 NAME

CAMPUSonline::ThesisElements::setThesisStatusByIDRequest

=head1 DESCRIPTION

Perl data type class for the XML Schema defined element
setThesisStatusByIDRequest from the namespace http://www.campusonline.at/thesisservice/basetypes.







=head1 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * token

 $element->set_token($data);
 $element->get_token();




=item * ID

 $element->set_ID($data);
 $element->get_ID();




=item * status

 $element->set_status($data);
 $element->get_status();




=item * statusDate

 $element->set_statusDate($data);
 $element->get_statusDate();





=back


=head1 METHODS

=head2 new

 my $element = CAMPUSonline::ThesisElements::setThesisStatusByIDRequest->new($data);

Constructor. The following data structure may be passed to new():

 {
   token =>  $some_value, # string
   ID =>  $some_value, # long
   status => $some_value, # SimpleStateType
   statusDate =>  $some_value, # dateTime
 },

=head1 AUTHOR

Generated by SOAP::WSDL

=cut

