package CAMPUSonline::ThesisTypes::DocumentClass;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.campusonline.at/thesisservice/basetypes' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %type_of :ATTR(:get<type>);
my %attr_of :ATTR(:get<attr>);
my %docUrl_of :ATTR(:get<docUrl>);

__PACKAGE__->_factory(
    [ qw(        type
        attr
        docUrl

    ) ],
    {
        'type' => \%type_of,
        'attr' => \%attr_of,
        'docUrl' => \%docUrl_of,
    },
    {
        'type' => 'CAMPUSonline::ThesisTypes::SimpleNameType',
        'attr' => 'CAMPUSonline::ThesisTypes::KeyAttr',
        'docUrl' => 'SOAP::WSDL::XSD::Typelib::Builtin::anyURI',
    },
    {

        'type' => 'type',
        'attr' => 'attr',
        'docUrl' => 'docUrl',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CAMPUSonline::ThesisTypes::DocumentClass

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
DocumentClass from the namespace http://www.campusonline.at/thesisservice/basetypes.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * type


=item * attr


=item * docUrl




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CAMPUSonline::ThesisTypes::DocumentClass
   type => $some_value, # SimpleNameType
   attr =>  { value => $some_value },
   docUrl =>  $some_value, # anyURI
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

