package CAMPUSonline::ThesisTypes::Metaclass;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.campusonline.at/thesisservice/basetypes' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %name_of :ATTR(:get<name>);
my %metaobj_of :ATTR(:get<metaobj>);

__PACKAGE__->_factory(
    [ qw(        name
        metaobj

    ) ],
    {
        'name' => \%name_of,
        'metaobj' => \%metaobj_of,
    },
    {
        'name' => 'CAMPUSonline::ThesisTypes::SimpleNameType',
        'metaobj' => 'CAMPUSonline::ThesisTypes::Metaobj',
    },
    {

        'name' => 'name',
        'metaobj' => 'metaobj',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CAMPUSonline::ThesisTypes::Metaclass

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
Metaclass from the namespace http://www.campusonline.at/thesisservice/basetypes.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * name


=item * metaobj




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CAMPUSonline::ThesisTypes::Metaclass
   name => $some_value, # SimpleNameType
   metaobj =>  { # CAMPUSonline::ThesisTypes::Metaobj
     type => $some_value, # SimpleTypeType
     attr =>  { value => $some_value },
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

