package CAMPUSonline::ThesisTypes::MetadataAttrKeySet;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.campusonline.at/thesisservice/basetypes' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %attrKeySet_of :ATTR(:get<attrKeySet>);
my %classAttrKeySet_of :ATTR(:get<classAttrKeySet>);

__PACKAGE__->_factory(
    [ qw(        attrKeySet
        classAttrKeySet

    ) ],
    {
        'attrKeySet' => \%attrKeySet_of,
        'classAttrKeySet' => \%classAttrKeySet_of,
    },
    {
        'attrKeySet' => 'CAMPUSonline::ThesisTypes::AttrKey',
        'classAttrKeySet' => 'CAMPUSonline::ThesisTypes::ClassAttrKeySet',
    },
    {

        'attrKeySet' => 'attrKeySet',
        'classAttrKeySet' => 'classAttrKeySet',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CAMPUSonline::ThesisTypes::MetadataAttrKeySet

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
MetadataAttrKeySet from the namespace http://www.campusonline.at/thesisservice/basetypes.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * attrKeySet


=item * classAttrKeySet




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CAMPUSonline::ThesisTypes::MetadataAttrKeySet
   attrKeySet => ,
   classAttrKeySet =>  { # CAMPUSonline::ThesisTypes::ClassAttrKeySet
     name => $some_value, # SimpleNameType
     attr => ,
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

