package CAMPUSonline::ThesisTypes::PlagiatsDoc;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.campusonline.at/thesisservice/basetypes' };

our $XML_ATTRIBUTE_CLASS = 'CAMPUSonline::ThesisTypes::PlagiatsDoc::_PlagiatsDoc::XmlAttr';

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %fileName_of :ATTR(:get<fileName>);
my %mimeType_of :ATTR(:get<mimeType>);
my %fileSize_of :ATTR(:get<fileSize>);
my %fileCreatedOn_of :ATTR(:get<fileCreatedOn>);
my %fileChangedOn_of :ATTR(:get<fileChangedOn>);
my %content_of :ATTR(:get<content>);

__PACKAGE__->_factory(
    [ qw(        fileName
        mimeType
        fileSize
        fileCreatedOn
        fileChangedOn
        content

    ) ],
    {
        'fileName' => \%fileName_of,
        'mimeType' => \%mimeType_of,
        'fileSize' => \%fileSize_of,
        'fileCreatedOn' => \%fileCreatedOn_of,
        'fileChangedOn' => \%fileChangedOn_of,
        'content' => \%content_of,
    },
    {
        'fileName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'mimeType' => 'CAMPUSonline::ThesisTypes::SimpleMimeType',
        'fileSize' => 'SOAP::WSDL::XSD::Typelib::Builtin::long',
        'fileCreatedOn' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        'fileChangedOn' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        'content' => 'SOAP::WSDL::XSD::Typelib::Builtin::base64Binary',
    },
    {

        'fileName' => 'fileName',
        'mimeType' => 'mimeType',
        'fileSize' => 'fileSize',
        'fileCreatedOn' => 'fileCreatedOn',
        'fileChangedOn' => 'fileChangedOn',
        'content' => 'content',
    }
);

} # end BLOCK




package CAMPUSonline::ThesisTypes::PlagiatsDoc::_PlagiatsDoc::XmlAttr;
use base qw(SOAP::WSDL::XSD::Typelib::AttributeSet);

{ # BLOCK to scope variables

my %type_of :ATTR(:get<type>);
my %prefered_of :ATTR(:get<prefered>);

__PACKAGE__->_factory(
    [ qw(
        type
        prefered
    ) ],
    {

        type => \%type_of,

        prefered => \%prefered_of,
    },
    {
        type => 'CAMPUSonline::ThesisTypes::SimplePlagRepDocType',
        prefered => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
    }
);

} # end BLOCK



1;


=pod

=head1 NAME

CAMPUSonline::ThesisTypes::PlagiatsDoc

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
PlagiatsDoc from the namespace http://www.campusonline.at/thesisservice/basetypes.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * fileName


=item * mimeType


=item * fileSize


=item * fileCreatedOn


=item * fileChangedOn


=item * content




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CAMPUSonline::ThesisTypes::PlagiatsDoc
   fileName =>  $some_value, # string
   mimeType => $some_value, # SimpleMimeType
   fileSize =>  $some_value, # long
   fileCreatedOn =>  $some_value, # dateTime
   fileChangedOn =>  $some_value, # dateTime
   content =>  $some_value, # base64Binary
 },



=head2 attr

NOTE: Attribute documentation is experimental, and may be inaccurate.
See the correspondent WSDL/XML Schema if in question.

This class has additional attributes, accessibly via the C<attr()> method.

attr() returns an object of the class CAMPUSonline::ThesisTypes::PlagiatsDoc::_PlagiatsDoc::XmlAttr.

The following attributes can be accessed on this object via the corresponding
get_/set_ methods:

=over

=item * type



This attribute is of type L<CAMPUSonline::ThesisTypes::SimplePlagRepDocType|CAMPUSonline::ThesisTypes::SimplePlagRepDocType>.

=item * prefered



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::boolean|SOAP::WSDL::XSD::Typelib::Builtin::boolean>.


=back




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

