package CAMPUSonline::ThesisTypes::state;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.campusonline.at/thesisservice/basetypes' };

our $XML_ATTRIBUTE_CLASS = 'CAMPUSonline::ThesisTypes::state::_state::XmlAttr';

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %from_of :ATTR(:get<from>);
my %to_of :ATTR(:get<to>);

__PACKAGE__->_factory(
    [ qw(        from
        to

    ) ],
    {
        'from' => \%from_of,
        'to' => \%to_of,
    },
    {
        'from' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        'to' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
    },
    {

        'from' => 'from',
        'to' => 'to',
    }
);

} # end BLOCK




package CAMPUSonline::ThesisTypes::state::_state::XmlAttr;
use base qw(SOAP::WSDL::XSD::Typelib::AttributeSet);

{ # BLOCK to scope variables

my %name_of :ATTR(:get<name>);
my %negate_of :ATTR(:get<negate>);

__PACKAGE__->_factory(
    [ qw(
        name
        negate
    ) ],
    {

        name => \%name_of,

        negate => \%negate_of,
    },
    {
        name => 'CAMPUSonline::ThesisTypes::SimpleStateType',
        negate => 'SOAP::WSDL::XSD::Typelib::Builtin::boolean',
    }
);

} # end BLOCK



1;


=pod

=head1 NAME

CAMPUSonline::ThesisTypes::state

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
state from the namespace http://www.campusonline.at/thesisservice/basetypes.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * from


=item * to




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CAMPUSonline::ThesisTypes::state
   from =>  $some_value, # dateTime
   to =>  $some_value, # dateTime
 },



=head2 attr

NOTE: Attribute documentation is experimental, and may be inaccurate.
See the correspondent WSDL/XML Schema if in question.

This class has additional attributes, accessibly via the C<attr()> method.

attr() returns an object of the class CAMPUSonline::ThesisTypes::state::_state::XmlAttr.

The following attributes can be accessed on this object via the corresponding
get_/set_ methods:

=over

=item * name



This attribute is of type L<CAMPUSonline::ThesisTypes::SimpleStateType|CAMPUSonline::ThesisTypes::SimpleStateType>.

=item * negate



This attribute is of type L<SOAP::WSDL::XSD::Typelib::Builtin::boolean|SOAP::WSDL::XSD::Typelib::Builtin::boolean>.


=back




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

