package CAMPUSonline::ThesisTypes::ClassAttrKeySet;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.campusonline.at/thesisservice/basetypes' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %name_of :ATTR(:get<name>);
my %attr_of :ATTR(:get<attr>);

__PACKAGE__->_factory(
    [ qw(        name
        attr

    ) ],
    {
        'name' => \%name_of,
        'attr' => \%attr_of,
    },
    {
        'name' => 'CAMPUSonline::ThesisTypes::SimpleNameType',
        'attr' => 'CAMPUSonline::ThesisTypes::AttrKey',
    },
    {

        'name' => 'name',
        'attr' => 'attr',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CAMPUSonline::ThesisTypes::ClassAttrKeySet

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
ClassAttrKeySet from the namespace http://www.campusonline.at/thesisservice/basetypes.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * name


=item * attr




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CAMPUSonline::ThesisTypes::ClassAttrKeySet
   name => $some_value, # SimpleNameType
   attr => ,
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

