package CAMPUSonline::ThesisTypes::PlagReport;
use strict;
use warnings;


__PACKAGE__->_set_element_form_qualified(1);

sub get_xmlns { 'http://www.campusonline.at/thesisservice/basetypes' };

our $XML_ATTRIBUTE_CLASS;
undef $XML_ATTRIBUTE_CLASS;

sub __get_attr_class {
    return $XML_ATTRIBUTE_CLASS;
}

use Class::Std::Fast::Storable constructor => 'none';
use base qw(SOAP::WSDL::XSD::Typelib::ComplexType);

Class::Std::initialize();

{ # BLOCK to scope variables

my %reportUUID_of :ATTR(:get<reportUUID>);
my %submissionDate_of :ATTR(:get<submissionDate>);
my %reportDate_of :ATTR(:get<reportDate>);
my %serviceName_of :ATTR(:get<serviceName>);
my %pop_of :ATTR(:get<pop>);
my %reportDoc_of :ATTR(:get<reportDoc>);

__PACKAGE__->_factory(
    [ qw(        reportUUID
        submissionDate
        reportDate
        serviceName
        pop
        reportDoc

    ) ],
    {
        'reportUUID' => \%reportUUID_of,
        'submissionDate' => \%submissionDate_of,
        'reportDate' => \%reportDate_of,
        'serviceName' => \%serviceName_of,
        'pop' => \%pop_of,
        'reportDoc' => \%reportDoc_of,
    },
    {
        'reportUUID' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'submissionDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        'reportDate' => 'SOAP::WSDL::XSD::Typelib::Builtin::dateTime',
        'serviceName' => 'SOAP::WSDL::XSD::Typelib::Builtin::string',
        'pop' => 'SOAP::WSDL::XSD::Typelib::Builtin::float',
        'reportDoc' => 'CAMPUSonline::ThesisTypes::PlagiatsDoc',
    },
    {

        'reportUUID' => 'reportUUID',
        'submissionDate' => 'submissionDate',
        'reportDate' => 'reportDate',
        'serviceName' => 'serviceName',
        'pop' => 'pop',
        'reportDoc' => 'reportDoc',
    }
);

} # end BLOCK







1;


=pod

=head1 NAME

CAMPUSonline::ThesisTypes::PlagReport

=head1 DESCRIPTION

Perl data type class for the XML Schema defined complexType
PlagReport from the namespace http://www.campusonline.at/thesisservice/basetypes.






=head2 PROPERTIES

The following properties may be accessed using get_PROPERTY / set_PROPERTY
methods:

=over

=item * reportUUID


=item * submissionDate


=item * reportDate


=item * serviceName


=item * pop


=item * reportDoc




=back


=head1 METHODS

=head2 new

Constructor. The following data structure may be passed to new():

 { # CAMPUSonline::ThesisTypes::PlagReport
   reportUUID =>  $some_value, # string
   submissionDate =>  $some_value, # dateTime
   reportDate =>  $some_value, # dateTime
   serviceName =>  $some_value, # string
   pop =>  $some_value, # float
   reportDoc =>  { # CAMPUSonline::ThesisTypes::PlagiatsDoc
     fileName =>  $some_value, # string
     mimeType => $some_value, # SimpleMimeType
     fileSize =>  $some_value, # long
     fileCreatedOn =>  $some_value, # dateTime
     fileChangedOn =>  $some_value, # dateTime
     content =>  $some_value, # base64Binary
   },
 },




=head1 AUTHOR

Generated by SOAP::WSDL

=cut

